[package]
name = "thoth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.6.3"
crossterm = { version = "0.27.0", features = ["bracketed-paste"] }
ratatui = "0.26.3"
tui-textarea = "0.4.0"
copypasta = "0.10.1"
anyhow = "1.0.86"

[dev-dependencies]
mockall = "0.11"
